### ISSUE TITLE
Crashes after run()

### ISSUE THREAD

**Issue by DaniilSkLi** [nobodywho-ooo/nobodywho#43]
When starting a scene from the editor window, the godot logo appears and then the window closes. There are no errors in the console.

https://github.com/user-attachments/assets/bcd2e455-864b-4bb2-a1ce-6fe3fddbb7e8

The script on NobodyWhoPromptChat call run() inside _ready()

[Model Llama 3.2 3B downloaded from README link](https://huggingface.co/bartowski/Llama-3.2-3B-Instruct-GGUF/resolve/main/Llama-3.2-3B-Instruct-Q4_K_M.gguf)

I don't understand what could be the problem 😕 

Godot: 4.3.stable from flatpak
Other PC specs:
OS: Debian 12.8, Gnome
CPU: Ryzen 5 5600X
GPU: RTX3050 8gb
RAM: 16gb and 32gb swap

**Comment by TheTrash** [comment]
"maybe try[ gemma 2 2b]( https://huggingface.co/bartowski/gemma-2-2b-it-GGUF/blob/main/gemma-2-2b-it-Q3_K_L.gguf) for now" 

I had the same bug, for some reason import the node with db in the scene fixed. Try also this.

**Comment by DaniilSkLi** [comment]
@TheTrash downloaded it, tried it, nothing changed :(

**Comment by TheTrash** [comment]
The db node has given some result? 
Can you share your project?

**Comment by volesen** [comment]
@DaniilSkLi, can you try the newest release (from GitHub releases)?

**Comment by AsbjornOlling** [comment]
I can't say with certainty, but I'm fairly sure the crash you got was caused by trying to allocate more VRAM than you have, because the context size was set really high by default.

In v3.1.0 (released just now), the context length is set to 4096 tokens by default, which is a fairly low context length. It was also made adjustable directly from godot, in case you need more or less context.

The release previous to that (v3.0.1, released yesterday), improves error messages by a lot. So if it should crash again, we get a better idea of why :innocent:

**Comment by AsbjornOlling** [comment]
> Hi there, there might be a race condition with The model being being read and when its being loaded (in the `run` call).
> 
> As Godot calls the children of a nodes `ready` function before calling ready on the parent node, you are actually trying to load the model before the system knows where the model is.
> 
> Nesting the NobodyWhoPromptChat under the NobodyWhoModel causes your crash.
> 
> What you want to do is this:
> 
> ![image](https://private-user-images.githubusercontent.com/56673512/391921524-b5d03588-7107-402b-8f22-dba5abc5b01f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMzc2OTEsIm5iZiI6MTczMzIzNzM5MSwicGF0aCI6Ii81NjY3MzUxMi8zOTE5MjE1MjQtYjVkMDM1ODgtNzEwNy00MDJiLThmMjItZGJhNWFiYzViMDFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAzVDE0NDk1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4MGJlYTQ3YzY1YjU1NjZjMGViNDAzMGMyNDI1MDcyYjhjOTk0MjVjM2Q3MjM4MTNmMmUxOWU5Yzg4OWJlN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GG-NyzsqFYADP9difol6SHv-7rrSa8GqzY3pxn34gNw)
> 
> Let me know if this helps you!

That issue was fixed in v2.0.3, so that's not it :innocent:

**Comment by DaniilSkLi** [comment]
@emilnorsker 
I tried swapping them around but still crashed. Now I put them as you have on the screenshot:
![screenshot](https://github.com/user-attachments/assets/0f753c40-56be-446e-a501-8c018d9f2d39)

And even added a delay in the script before running the run function:
```gdscript
func _ready() -> void:
    await get_tree().create_timer(1.0).timeout
    run()
```
With the delay, the game starts, I see the text "Test" from the `RichTextLabel` node, but after a second of delay, the window still closes without any errors.

**Comment by DaniilSkLi** [comment]
@volesen 
> @DaniilSkLi, can you try the newest release (from GitHub releases)?

I downloaded version 3.1.0 from the releases page, deleted the old one from the addons folder and unzipped 3.1.0, nothing changed, still no errors and still the same window closes when running the `run` function

**Comment by DaniilSkLi** [comment]
@AsbjornOlling 
> I can't say with certainty, but I'm fairly sure the crash you got was caused by trying to allocate more VRAM than you have, because the context size was set really high by default.
> 
> In v3.1.0 (released just now), the context length is set to 4096 tokens by default, which is a fairly low context length. It was also made adjustable directly from godot, in case you need more or less context.
> 
> The release previous to that (v3.0.1, released yesterday), improves error messages by a lot. So if it should crash again, we get a better idea of why 😇

I don't think so. There is no delay after running the `run` function for the memory to fill, overflow, and then crash. The window closes immediately after the `run` function is started. I also opened `nvtop` and the video card memory did not fill up in any way. Also in the `NobodyWhoPromptChat` node I tried setting `Context Length` 1024, 256 and even 1, it had no effect.

**Comment by DaniilSkLi** [comment]
[Here](https://drive.google.com/file/d/1vtLsubZT2qSiGL0ka3K0sElceqmDVqkN/view?usp=sharing) are the project files if you need, except for the model, as it is big, but I tried as I wrote above, the model Llama 3.2 3B with README, and also gemma2 2b.

**Comment by AsbjornOlling** [comment]
> I also have the same issue, but on Windows, even in 4.0

I'm not convinced that it's the same root cause, even though it's the same symptom (the worker thread crashes).

the `vkCreateSwapchainKHR` error seems to be caused by other overlay programs, like e.g. steam overlay or rivatuner statistic server. 
... at least that's what I get from reading [this blender issue](https://projects.blender.org/blender/blender/issues/128636)

Do you have something like that installed on your machine?

**Comment by spoutnickgp** [comment]
Hum, I had discord running, so it might be that. When it's not running, I always get the second error though:
```
================================================================
CrashHandlerException: Program crashed with signal 11
Engine version: Godot Engine v4.3.stable.official (77dcf97d82cbfe4e4615475fa52ca03da645dbd8)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] error(-1): no debug info in PE/COFF executable
[2] error(-1): no debug info in PE/COFF executable
[3] error(-1): no debug info in PE/COFF executable
[4] error(-1): no debug info in PE/COFF executable
[5] error(-1): no debug info in PE/COFF executable
[6] error(-1): no debug info in PE/COFF executable
-- END OF BACKTRACE --
================================================================
```
